[fix] Fix that RSS is never returned on Windows
apify/ps-tree pull request #1
Opened 2021-05-03 04:07 UTC by polikeiji

RSS is always returned as NaN, and it causes that the "mainProcessBytes" in the response of "Apify.getMemoryInfo" is always returned as "NaN".

2021-05-03 14:24 UTC, jancurn requested changes
Many thanks for your fix! Please see a small comment

2021-05-03 14:24 UTC, jancurn commented on index.js
> +          columns[4] = parseInt(columns[3], 10);
It would be safer to just skip "Status" in the WMIC call above. In case WMIC shows some non-empty string for it, this code here will fail.

2021-05-03 14:24 UTC, pocesar commented on index.js
> +          // See: https://docs.microsoft.com/ja-jp/windows/win32/cimwin32prov/win32-process?redirectedfrom=MSDN
nitpick: change the doc to en-us

2021-05-03 14:54 UTC, polikeiji commented
@pocesar 
Thank you for your comment! I updated it. Please review them when you have time.

2021-05-04 11:28 UTC, jancurn approved these changes
Looks good, thanks!

2021-05-04 11:28 UTC, merged

2021-05-04 11:55 UTC, jancurn commented
Merged and published, will get to Apify SDK soon - https://github.com/apify/apify-js/pull/1017